apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- service-account.yaml
- roles.yaml
- service.yaml
- route.yaml
- hw-event-proxy.yaml
- consumer.yaml
replicas:
- count: 1
  name: consumer
- count: 1
  name: hw-event-proxy

secretGenerator:
- literals:
  - username=admin
  - password=admin
  - hostaddr=127.0.0.1
  name: redfish-basic-auth
  namespace: cloud-native-events
  type: Opaque
