apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- service-account.yaml
- roles.yaml
- service.yaml
- route.yaml
- hw-event-proxy.yaml
- consumer.yaml
replicas:
- count: 1
  name: consumer
- count: 1
  name: hw-event-proxy
images:
- name: cloud-event-proxy
  newName: quay.io/jacding/cloud-event-proxy
  newTag: latest
- name: cloud-native-event-consumer
  newName: quay.io/jacding/cloud-native-event-consumer
  newTag: latest
- name: hw-event-proxy
  newName: quay.io/jacding/hw-event-proxy
  newTag: latest

secretGenerator:
- literals:
  - username=root
  - password=calvin
  - hostaddr=10.19.28.42
  name: redfish-basic-auth
  namespace: cloud-native-events
  type: Opaque
