apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

# Use dummy credentials since ci lab does not have access to Redfish hardwares
secretGenerator:
- name: redfish-basic-auth
  namespace: cloud-native-events
  type: Opaque
  literals:
  - username=admin
  - password=admin
  - hostaddr=127.0.0.1
