name: hw-event-proxy
on: [push, pull_request]

defaults:
  run:
    working-directory: ./hw-event-proxy

jobs:
  golangci:
    name: Linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: tidy
        run: go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Caching conflicts happen in GHA, so just disable for now
          skip-pkg-cache: true
          skip-build-cache: true
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.41
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Test Scripts
      run: |
        make gha


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
